### PR TITLE
Adding security layer file

### PR DESCRIPTION
**Pull request by el3232**

### CODE REVIEW

**Comment by el3232** [comment]
Yes, I made a mistake by committing the changes to SeattleTestbed rather than my forked repository. I'm just learning git and github and would love to talk about how to think about adding the correct files. It was my understanding that while RUNNABLE should be built anew each time, I wasn't sure how to correctly reflect that the security layer should be in the RUNNABLE folder (if it should). 

How can we discuss? Also, my closing the pull request, have I already "removed" all the files I added?

**Comment by JustinCappos** [comment]
Sure, that branch was not merged.

Can you tell me more about what you are hoping to accomplish with the pull
request?  What is the security layer you are adding for?

**Comment by el3232** [comment]
Essentially, I am adding the security layer as part of an ISP assignment. I wanted to contextualize it rather than just upload the single file. Is there a best practice or a general assumption to follow with something like this? Again, I am new to this and am just trying to figure out how it would be in production.

**Comment by JustinCappos** [comment]
Sorry for the delayed response.  Please look at your PR (pull request) and
see if there are extra files added.  I would pull and merge your files
directly.

You can also use the view option on the pull request in order to see what
the eventual files will look like.

**Pull request closed without merging**
